apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-set
  namespace: argocd
  labels:
    group: auto3
spec:
  project: tikal
  source:
    repoURL: git@github.com:tikal/tikal_helm_deploy
    path: helm/product-appset-chart
    targetRevision: auto3
    helm:
      valueFiles:
        - '../env-values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:

    automated:
      prune: true
      selfHeal: true
