## number of instances
##
replicaCount: 1

## restart policy for all containers
##
restartPolicy: Always

cronjob:
  name: argocd-ecr-updater-cronjob
  argoNamespace: argocd
  awsRegion: eu-west-1
  awsAccount: "607827849963"
  argocdRepoSecretName: argocd-ecr-access
  cronExpression: 0 0/6 * * *

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::607827849963:role/argocd-get-oci-access-sultan
  




resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

priorityClassName: ""

nodeSelector: {}
#  kubernetes.io/os: linux
#  kubernetes.io/arch: amd64

tolerations: {}

podAnnotations: {}
#  sidecar.istio.io/inject: "false"
#  prometheus.io/scrape: "true"
#  prometheus.io/path: "metrics"
#  prometheus.io/port: "8080"

service:
  httpPort: "8080"

affinity: {}

## The name of a secret in the same kubernetes namespace which contain values to be added to the environment
envFromSecret: ""

extraEnvSecrets: {}

# A list of secrets and their paths to mount inside the pod
# This is useful for mounting certificates for security
secretMounts: []
