apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "true"
  users.anonymous.enabled: "true"
  url: "https://argocd-{{ .Values.cluster_name }}.{{ .Values.argocd.ingress.domain }}"
  ui.bannercontent: "{{ .Values.cluster_name }} cluster"
  repositories: |
    - name: tikal-helm-charts
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: github-repo-secret
      type: git
      url: git@github.com:tikal/tikal_helm_deploy.git
    - name: sonatype
      type: helm
      url: https://sonatype.github.io/helm3-charts/
    - name: eks
      type: helm
      url: https://aws.github.io/eks-charts
    - name: autoscaler
      type: helm
      url: https://kubernetes.github.io/autoscaler
    - name: external-secrets
      type: helm
      url: https://external-secrets.github.io/kubernetes-external-secrets/
    - name: bitnami
      type: helm
      url: https://charts.bitnami.com/bitnami
    - name: ingress-nginx
      type: helm
      url: https://kubernetes.github.io/ingress-nginx
    - name: datadog
      type: helm
      url: https://helm.datadoghq.com
    - name: kube2iam
      type: helm
      url: https://jtblin.github.io/kube2iam/
  {{- if .Values.argocd.sso.enabled }}
  dex.config: |
    connectors:
    - type: microsoft
      id: microsoft
      name: tikal
      config:
        clientID: {{ .Values.argocd.sso.clientid }}
        clientSecret: {{ .Values.argocd.sso.clientsecret }}
        redirectURI: https://argocd-{{ .Values.cluster_name }}.{{ .Values.argocd.ingress.domain }}/api/dex/callback
        tenant: {{ .Values.argocd.sso.tenant }}
        groups:
          - DevOps-Azure
  {{- end }}
