
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.argocd.project }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .Values.argocd.project | title }}
  destinations:
    - namespace: "*"
      server: {{ .Values.cluster_address }}
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
