#https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml

## Controller
controller:
  # If changing the number of replicas you must pass the number as ARGOCD_CONTROLLER_REPLICAS as an environment variable
  replicas: 2
  enableStatefulSet: true


  env:
    - name: "ARGOCD_CONTROLLER_REPLICAS"
      value: "2"

## Redis
redis:
  enabled: false

redis-ha:
  enabled: true
  # Check the redis-ha chart for more properties
  exporter:
    enabled: false

## Server
server:
  replicas: 2
  configEnabled: true
  config:
     repositories: |
       - name: tikal-helm-charts
         sshPrivateKeySecret:
           key: sshPrivateKey
           name: github-repo-secret
         url: git@github.com:tikal/tikal_helm_deploy.git
       - name: sonatype
         type: helm
         url: https://sonatype.github.io/helm3-charts/
       - name: eks
         type: helm
         url: https://aws.github.io/eks-charts
       - name: autoscaler
         type: helm
         url: https://kubernetes.github.io/autoscaler
       - name: external-secrets
         type: helm
         url: https://external-secrets.github.io/kubernetes-external-secrets/
       - name: bitnami
         type: helm
         url: https://charts.bitnami.com/bitnami


  ## Projects
  ## reference: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
  additionalProjects:
  - name: tikal
    namespace: argocd
    description: tikal Project
    sourceRepos:
    - "*"
    destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
