apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tikal-secrets
  namespace: tikal
spec:
  backendType: secretsManager
  # roleArn: arn:aws:iam::607827849963:role/external-secrets_role_{{ .Values.cluster_name }}
  region: {{ .Values.region }}
  data:
    - key: {{ .Values.cluster_name }}-tikal-secrets
      name: application-kamus.properties
      property: kamus
    - key: {{ .Values.cluster_name }}-tikal-secrets
      name: POSTGRES_PASS
      property: POSTGRES_PASS
    - key: {{ .Values.cluster_name }}-tikal-secrets
      name: POSTGRES_USER
      property: POSTGRES_USER
    - key: {{ .Values.cluster_name }}-tikal-secrets
      name: GRAPHQL_DB_PASSWORD
      property: GRAPHQL_DB_PASSWORD
    - key: {{ .Values.cluster_name }}-tikal-secrets
      name: GRAPHQL_DB_USER
      property: GRAPHQL_DB_USER

