---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argocd-ecr-updater.serviceAccountName" . }}-configure-rbac
subjects:
  - kind: ServiceAccount
    name: {{ include "argocd-ecr-updater.serviceAccountName" . }} # we are just giving our deafult account more access OR  you can Reference to upper's `metadata.name`
    namespace: {{ .Release.Namespace }} 
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io