{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "argocd-ecr-updater.fullname" . }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: 
    {{- range $key, $value := .Values.serviceAccount.annotations }}
     {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  labels:
    chart: {{ template "argocd-ecr-updater.chart" . }}
    app: {{ template "argocd-ecr-updater.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
- name: {{ .name }}
  {{- end }}
{{- end }}
{{- end }}
